// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl1NvbfGomQG2tV01jS_0iUTZgJ0wEhrE',
    appId: '1:645500611135:web:9d6bbb0ab0d307fa5f668a',
    messagingSenderId: '645500611135',
    projectId: 'chatapp-77e8e',
    authDomain: 'chatapp-77e8e.firebaseapp.com',
    storageBucket: 'chatapp-77e8e.appspot.com',
    measurementId: 'G-845PXD8604',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtAoTeRIsyD9DeUQObHbzfZ0LY0r_U0LI',
    appId: '1:645500611135:android:b5b07f1ab69745865f668a',
    messagingSenderId: '645500611135',
    projectId: 'chatapp-77e8e',
    storageBucket: 'chatapp-77e8e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAFxPyYQaAHxSNEpjsJpHo_cDapDJiBRQ',
    appId: '1:645500611135:ios:e4d1f21ac1c967dc5f668a',
    messagingSenderId: '645500611135',
    projectId: 'chatapp-77e8e',
    storageBucket: 'chatapp-77e8e.appspot.com',
    iosBundleId: 'com.example.firebaseChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAFxPyYQaAHxSNEpjsJpHo_cDapDJiBRQ',
    appId: '1:645500611135:ios:ee2f1b0d2a31f4e05f668a',
    messagingSenderId: '645500611135',
    projectId: 'chatapp-77e8e',
    storageBucket: 'chatapp-77e8e.appspot.com',
    iosBundleId: 'com.example.firebaseChatApp.RunnerTests',
  );
}
